#config.yaml for ichorCNA_offtarget.snakefile
#Ha Lab
#Fred Hutchinson Cancer Research Center

#There might be a problem in code/ichorCNA_offtarget.R with chromosome naming,
#perhaps just if bam files use UCSC naming.  --Anna 10/18/19

#SELECT CHROMOSOMES WHICH MATCH NAMING IN BAM FILES
chrs:
  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y
  #chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX

#SELECT GENOME BUILD USED FOR REFERENCE GENOME USED IN ALIGNMENT OF BAM FILES
ichorCNA_genomeBuild:
    hg19
    #hg38

#SELECT CENTROMERE CORRESPONDING TO REFERENCE GENOME USED IN ALIGNMENT OF BAM FILES
ichorCNA_centromere:
    {/path/to/}ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt
    #{/path/to/}ichorCNA/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt

#SELECT BIN SIZE
binSize:  1000000

#SELECT NORMAL PANEL, MATCHING BIN SIZE AND REFERENCE GENOME USED IN ALIGNMENT, OR "None"
ichorCNA_normalPanel: None

#SELECT GC WIG AND MAP WIG TO MATCH REFERENCE GENOME USED IN ALIGNMENT AND BIN SIZE
ichorCNA_gcWig: {/path/to/}ichorCNA/inst/extdata/gc_hg19_1000kb.wig
ichorCNA_mapWig:  {/path/to/}ichorCNA/inst/extdata/map_hg19_1000kb.wig

#SELECT BED FILE OF TARGETED REGIONS, OR "NULL"
ichorCNA_targets:  NULL

#SELECT OUPUT NAMING STYLE
ichorCNA_genomeStyle:
    #UCSC
    NCBI

#SELECT NON-TUMOR FRACTION RESTART VALUES (higher values should be included for cfDNA)
ichorCNA_normal:
    c(0.01)
    #c(0.25, 0.5, 0.75)

#SELECT PLOIDY RESTART VALUES
ichorCNA_ploidy:  c(2,3,4)

#SELECT SEGMENTATION PARAMS (higher #s = fewer segments; # of 9s must match # of 0s)
ichorCNA_txnE:  0.9999
ichorCNA_txnStrength:  10000

#paths to libraries and scripts
ichorCNA_libdir: {/path/to/}ichorCNA
ichorCNA_rscript:  code/runIchorCNA_offtarget.R
#PROVIDE PATH TO READ COUNTER BINARY
readCounterScript:  {/path/to/}bin/readCounter
offTarget_script:  code/ichorCNA_offtarget.R

#other ichor settings
ichorCNA_chrs:  c(1:22, \"X\")
ichorCNA_fracReadsInChrYForMale: 0.002
# chrs used for training ichorCNA parameters, e.g. tumor fraction.
ichorCNA_chrTrain:  c(1:22)
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
# states to use for subclonal CN
ichorCNA_scStates:  c(1,3)
# set maximum copy number to use
ichorCNA_maxCN:  10
# TRUE/FALSE to include homozygous deletion state
ichorCNA_includeHOMD: FALSE
# Exclude solutions if total length of subclonal CNAs > this fraction of the genome
ichorCNA_maxFracGenomeSubclone:  0.5
# Exclude solutions if total length of subclonal CNAs > this fraction of total CNA length
ichorCNA_maxFracCNASubclone:  0.5
ichorCNA_plotFileType:  pdf
ichorCNA_plotYlim:  c(-2,4)
